GET http://localhost:3001/

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/100

###
DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Syed Taqi Haider",
    "number": "07539913355"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Dave Grohl",
    "whoDis": "07539913355"
}

###
GET http://localhost:3001/api/cows HTTP/1.1
